<a href="https://colab.research.google.com/github/MartyWeissman/PythonForMathematics/blob/main/Math152_Feb18_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Teaching notebook, Feb 18, 2021

Introduction to Numpy!

Outline:

1.  Creating numpy ndarrays
2.  Coercing types and overflow
3.  Broadcasting math functions
4.  Cumulative sum.  Approximating $\gamma$
4.  Plotting a function (line plots)


In [2]:
import numpy as np

In [3]:
np.sqrt(1000)

31.622776601683793

In [5]:
np.random.random(5) # An array of random numbers between 0 and 1

array([0.28877017, 0.82633799, 0.70657179, 0.81952535, 0.39004058])

Numpy ndarrays ("ndarray" is an "n-dimensional array")

In [7]:
A = np.array([1,2,3,4,5])

In [8]:
print(A)

[1 2 3 4 5]


In [9]:
L = [1,2,3,4,5]

In [10]:
print(L)

[1, 2, 3, 4, 5]


In [11]:
type(L)

list

In [12]:
type(A)

numpy.ndarray

In [13]:
A[2]

3

In [14]:
type(A[2])

numpy.int64

In [16]:
L = [1, 'S', 3.7]

In [17]:
type(L)

list

In [18]:
type(L[0])

int

In [19]:
type(L[1])

str

In [20]:
type(L[2])

float

In [21]:
A = np.array([1,'S',3.7])

In [22]:
print(A)

['1' 'S' '3.7']


Numpy arrays must have all terms of the same type!!

It will try to force this, when possible.

In [24]:
n = np.int64(37)

In [25]:
n

37

In [26]:
type(n)

numpy.int64

In [27]:
n**10

4808584372417849

In [28]:
37**10

4808584372417849

In [29]:
n**100

-1901415581956121743

In [30]:
37**100

6609557828843866774348296857793615320986068325257944996730965130260195627493490637048004105256563742994070037769599882399012397170569200279466412758131334001

## Broadcasting functions!

In [31]:
A = np.array([1,2,3,4,5])

In [32]:
print(A)

[1 2 3 4 5]


In [33]:
type(A)

numpy.ndarray

In [35]:
2*[1,2,3,4,5]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [36]:
2*A

array([ 2,  4,  6,  8, 10])

In [37]:
np.sin(A)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [38]:
np.sin(A*A)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175])

In [39]:
A*A

array([ 1,  4,  9, 16, 25])

The Euler-Mascheroni constant is
$$\gamma = \lim_{N \rightarrow \infty} \left( \sum_{n=1}^N \frac{1}{n} - \log(N) \right).$$

In [42]:
A = np.arange(1,1000000.0)

In [43]:
A[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
reciprocals = 1/A
print(reciprocals[:10])

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1       ]


In [45]:
logarithms = np.log(A)
print(logarithms[:10])

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [46]:
rec_sums = np.cumsum(reciprocals)

In [47]:
rec_sums[:10]

array([1.        , 1.5       , 1.83333333, 2.08333333, 2.28333333,
       2.45      , 2.59285714, 2.71785714, 2.82896825, 2.92896825])

In [48]:
gamma_approx = rec_sums - logarithms
print(gamma_approx[:10])

[1.         0.80685282 0.73472104 0.69703897 0.67389542 0.65824053
 0.64694699 0.6384156  0.63174368 0.62638316]


In [49]:
gamma_approx[-1]

0.5772161649012162

In [50]:
np.euler_gamma

0.5772156649015329