<a href="https://colab.research.google.com/github/MartyWeissman/PythonForMathematics/blob/main/Math152_Feb9_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Math 152, Teaching notebook, Feb 9, 2021

Lists, tuples, and numpy arrays.

In [90]:
import numpy as np

In [91]:
L = [1,2,3,4] # A plain Python list.
T = (1,2,3,4) # A Python tuple
A = np.array([1,2,3,4]) # A numpy array.

In [92]:
L[2]

3

In [93]:
T[2]

3

In [94]:
A[2]

3

In [95]:
L[2] = -3

In [96]:
print(L)

[1, 2, -3, 4]


In [97]:
T[2] = -3

TypeError: ignored

In [112]:
L = [1,2,-3,4]
M = L
L = [2,4,6]

In [113]:
print(L)

[2, 4, 6]


In [114]:
print(M)

[1, 2, -3, 4]


In [102]:
print(L)

[1, 2.5, -3, 4]


In [103]:
print(M)

[1, 2.5, -3, 4]


In [104]:
a = 3
b = a
a = 2

In [105]:
print(a)

2


In [106]:
print(b)

3


## Start here now!

In [115]:
A

array([1, 2, 3, 4])

In [116]:
type(A)

numpy.ndarray

In [117]:
type(A[0])

numpy.int64

In [118]:
B = A
A[1] = 7
print(A)
print(B)

[1 7 3 4]
[1 7 3 4]


In [123]:
A[1] = 5.7

In [124]:
print(A)

[1 5 3 4]


In [127]:
A.sum() # Sum "method"

13

In [128]:
print(L)

[2, 4, 6]


In [129]:
L.sum()

AttributeError: ignored

In [130]:
sum(L)

12

In [132]:
L = [6,2,3,5,13]

In [133]:
L.sort() # sort method.  Changes the list!

In [134]:
print(L)

[2, 3, 5, 6, 13]


In [140]:
np.random.choice(['A','B'],10)

array(['A', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'A'], dtype='<U1')

In [135]:
np.random.random(10)

array([0.47717033, 0.47390068, 0.85238594, 0.08980733, 0.54787138,
       0.58122397, 0.57640498, 0.3560591 , 0.13502786, 0.65642672])

In [136]:
R = np.random.random(1000000)

In [137]:
R.sum()

500559.64935464074

In [138]:
%timeit R.sum()

The slowest run took 4.27 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 355 µs per loop


In [143]:
[1,2,3] + [3,4,5]

[1, 2, 3, 3, 4, 5]

In [145]:
25*np.array([3,4,5])

array([ 75, 100, 125])

## Numerical integration.

Let $f$ be a nice real-valued function whose domain contains the interval $[a,b]$.  Let $N$ be a large integer, and let $w = (b-a) / N$, the "width" in what follows.  We can approximate $\int_a^b f(x) dx$ by the (left) Riemann sum:
$$S = \sum_{n=0}^{N-1} (w \cdot f(a + wn)).$$
Let's implement this as a function `Riemann_sum`

In [146]:
def Riemann_sum(f,a,b,N):
  width = (b-a) / N
  x_array = np.arange(a,b,width)[:-1]
  height_array = f(x_array)
  area_array = width * height_array
  return area_array.sum()

In [154]:
def f(x):
  return 1/(x+1)

In [156]:
Riemann_sum(f,0,1,1000000)

0.6931469305597577

In [ ]:
def Gaussian(x, mu=0, sigma=1):
  '''
  Returns the Gaussian (bell curve, or normal distribution)
  evaluated at x.  The Gaussian has mean mu and 
  standard deviation sigma.

  See https://en.wikipedia.org/wiki/Normal_distribution
  '''
  normalizer = 1/(sigma*np.sqrt(2*np.pi))
  x_adjusted = (x - mu) / sigma
  return normalizer * np.exp(-0.5 * x_adjusted**2)

In [ ]:
x_list = np.arange(-5,5,0.1)
y_list = Gaussian(x_list)

In [ ]:
import matplotlib.pyplot as plt
plt.plot(x_list, y_list)

In [ ]:
Riemann_sum(Gaussian, 0, 1, N=1000)

The trapezoidal rule gives a better approximation, usually, by approximating the area under the curve by trapezoids rather than rectangles.  The formula is
$$T = \sum_{n = 0}^{N-1} \left( w \cdot \frac{ f(a+wn) + f(a+w(n+1)) }{2} \right).$$