<a href="https://colab.research.google.com/github/MartyWeissman/PythonForMathematics/blob/main/Math_152_Feb23_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Math 152, Feb 23, 2021 Teaching Notebook

Numpy and linear algebra

In [50]:
import numpy as np # We're going to use numpy a lot!

In [56]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
I = np.eye(3,dtype=int)
R = np.random.random((3,3))
S = np.random.choice([0,1],(5,5))
print('M is \n', M)
print('I is \n', I)
print('R is \n', R)
print('S is \n', S)

M is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
I is 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
R is 
 [[0.46225686 0.82828675 0.2578901 ]
 [0.03089447 0.60190319 0.33670124]
 [0.13894141 0.93218132 0.4396778 ]]
S is 
 [[1 1 0 0 0]
 [0 1 1 0 0]
 [0 0 0 0 1]
 [0 0 1 1 0]
 [1 1 0 1 0]]


In [60]:
M[2,:] # Row 1 of M

array([7, 8, 9])

In [61]:
M[:,2] # Column 2 of M

array([3, 6, 9])

In [62]:
M*M

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [63]:
M.dot(M)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [64]:
M.trace()

15

In [65]:
M.diagonal()

array([1, 5, 9])

# Computing matrix multiplication

If $A = (a_{ij})$ and $B = (b_{ij})$ are two matrices, then $A \cdot B$ is the matrix $C = (c_{ij})$ with
$$c_{ij} = \sum_{k = 1}^m a_{ik} b_{kj}.$$

For this to "work", the number of columns of $A$ must equal the number of rows of $B$ -- this is the number $m$ in the above formula.

In [ ]:
A = np.random.random((3,4)) # 3 rows and 4 columns
print(A)

In [ ]:
def mat_mult(A,B):
  '''
  Compute the product of two matrices.
  Check their shape first!
  '''

  return C

# Computing the determinant by row operations

The determinant is a function $det$ which takes as input a square matrix and outputs a single number.  It satisfies a bunch of cool properties, including:

1.  If you switch two rows of the matrix, the determinant switches sign (i.e., gets multiplied by $-1$).

2.  If you add a multiple of one row to another row, the determinant doesn't change.

3.  If you scale a row by a number $\lambda$, then the determinant gets multiplied by $\lambda$.

4.  The determinant of the identity matrix equals 1.

In fact, $det$ is the only function which satisfies these properties!  A consequence of these properties is the following:

*Fact:* If a square $n \times n$ matrix $A$ has a single nonzero entry $a$ in the first column, and $a$ lies in the top row, then $det(A) = a \cdot det(B)$, where $B$ is the $(n-1) \times (n-1)$ matrix on the bottom-right.

$$det \left( \begin{array}{c|c} a & U \\ \hline 0 & B \end{array} \right) = a \cdot det(B).$$

We'll use this to create a pretty fast determinant-computer.  Not as fast as the built-in of course!


In [66]:
np.linalg.det(np.random.random((100,100)))

1.4800002212370802e+26

In [68]:
%timeit np.linalg.det(np.random.random((1000,1000)))

/usr/local/lib/python3.6/dist-packages/numpy/linalg/linalg.py:2159: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)


10 loops, best of 3: 58.1 ms per loop


In [70]:
np.flatnonzero(np.array([0,1,0,0,2,3]))

array([1, 4, 5])

In [71]:
def find_nonzero(A):
  '''
  Takes a square (n x n) matrix A as input.
  Looks for an entry in the first column which is nonzero.
  Returns -1 if no such entry is found.
  Otherwise, returns the index of this entry.
  '''
  first_column = A[:,0]
  nz = np.flatnonzero(first_column)
  if len(nz)>0:
    return nz[0]
  else:
    return -1

In [76]:
S = np.random.choice([0,1],(5,7))
print(S)

[[0 1 1 1 1 1 0]
 [1 1 0 0 0 1 0]
 [1 1 1 0 0 1 1]
 [1 1 0 0 1 0 0]
 [1 1 1 1 1 0 1]]


In [78]:
S.shape[0]

5

In [75]:
find_nonzero(S)

2

In [ ]:
def switch_rows(A,i,j):
  '''
  Switches rows i and j in a matrix A.
  '''
  return new_A

In [ ]:
def add_rowmult(A,i,j,s):
  '''
  Adds s times the jth row to the ith row of A.
  '''
  return new_A

In [ ]:
def scale_row(A,i,s):
  '''
  Scales row i of A by the scalar s.
  '''
  return new_A

In [116]:
def det(A, verbose = True):
  '''
  Returns the determinant of A.
  '''
  if type(A) == np.ndarray:
    if len(A.shape) != 2:
      raise ValueError('Input must be a matrix or scalar')
    if A.shape[0] != A.shape[1]:
      raise ValueError('Matrix must be square!')
    if A.shape[0] == 1:
      return A[0,0]
  else:
    A = np.float(A) # try to convert to float.
    return A

  # Step 1:  Look for a nonzero entry in the first column
  nz_index = find_nonzero(A)

  # If every entry in the first column is zero, the determinant is zero.
  if nz_index == -1:
    if verbose:
      print('No nonzero entry found in first column.  Det = 0')
    return 0
  if verbose:
    print('Nonzero entry found in row {} of matrix.'.format(nz_index))
    print(A)

  # Step 2:  Switch rows so that there's a nonzero entry in the top-left corner.
  A_new = A.copy()
  if verbose: 
    print('\n ---------------------- \n')
    print('Switching row 0 and row {}'.format(nz_index))
  A_new[0,:] = A[nz_index,:]
  A_new[nz_index,:] = A[0,:]
  if nz_index == 0:
    if verbose:
      print('No row-switch needed.')
    multiplier = 1
  else:
    if verbose:
      print('Determinant will be multiplied by -1')
    multiplier = -1


  if verbose: 
    print('\n ---------------------- \n')
    print('New matrix is...')
    print(A_new)

  # Now A_new is the same as A, but with nonzero entry in top-left.
  # Step 3:  Scale first row so that top-left corner is 1.
  scalar = A_new[0,0]
  multiplier = multiplier * scalar
  A_new[0,:] = (1/scalar) * A_new[0,:]
  if verbose:
    print('\n ---------------------- \n')
    print('Scaling first row by {}.  New matrix is...'.format(scalar))
    print(A_new)

  # Step 4:  Add multiples of row 0 to all other rows, to make first column 1,0,0,...0.
  num_rows = A_new.shape[0]
  for row in range(1,num_rows):
    A_new[row,:] = A_new[row,:] - A_new[row,0]*A_new[0,:] # Subtract off multiple of 0th row from given row.
  # Result is matrix with first column 1,0,0,...,0.
  if verbose:
    print('\n ---------------------- \n')
    print('Subtracting multiples of first row from others.  New matrix is...')
    print(A_new)

  # Step 5:  Compute determinant in terms of bottom-right matrix (recursive function call!)
  B = A_new[1:, 1:]
  if verbose:
    print('\n ---------------------- \n')
    print('Determinant is now computed as {} times the determinant of ...'.format(multiplier))
    print(B)
  return multiplier * det(B)


In [113]:
R = np.random.random((5,5)) * np.random.choice([0,1,1,1],(5,5))
print(R)

[[0.         0.21232098 0.99063212 0.72625309 0.24269324]
 [0.         0.8138585  0.12940067 0.06594133 0.21433889]
 [0.39948746 0.66408334 0.67688451 0.63753753 0.48291629]
 [0.         0.67532037 0.46145187 0.         0.18344733]
 [0.98866517 0.78122639 0.         0.77854702 0.61089788]]


In [117]:
np.linalg.det(R)

-0.013724649705939344

In [118]:
det(R)

Nonzero entry found in row 2 of matrix.
[[0.         0.21232098 0.99063212 0.72625309 0.24269324]
 [0.         0.8138585  0.12940067 0.06594133 0.21433889]
 [0.39948746 0.66408334 0.67688451 0.63753753 0.48291629]
 [0.         0.67532037 0.46145187 0.         0.18344733]
 [0.98866517 0.78122639 0.         0.77854702 0.61089788]]

 ---------------------- 

Switching row 0 and row 2
Determinant will be multiplied by -1

 ---------------------- 

New matrix is...
[[0.39948746 0.66408334 0.67688451 0.63753753 0.48291629]
 [0.         0.8138585  0.12940067 0.06594133 0.21433889]
 [0.         0.21232098 0.99063212 0.72625309 0.24269324]
 [0.         0.67532037 0.46145187 0.         0.18344733]
 [0.98866517 0.78122639 0.         0.77854702 0.61089788]]

 ---------------------- 

Scaling first row by 0.399487459459653.  New matrix is...
[[1.         1.66233838 1.69438238 1.59588873 1.20883968]
 [0.         0.8138585  0.12940067 0.06594133 0.21433889]
 [0.         0.21232098 0.99063212 0.726253

-0.013724649705939345